//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sessia1.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agents()
        {
            this.sales = new HashSet<sales>();
        }
    
        public int id_agent { get; set; }
        public string title { get; set; }
        public Nullable<int> id_agent_type { get; set; }
        public string address { get; set; }
        public string inn { get; set; }
        public string kpp { get; set; }
        public string director_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string logo { get; set; }
        public Nullable<int> priority { get; set; }
    
        public virtual agent_types agent_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales> sales { get; set; }
    }
}
