//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sessia1.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.sales = new HashSet<sales>();
        }
    
        public int id_product { get; set; }
        public string title { get; set; }
        public Nullable<int> id_prod_type { get; set; }
        public string article_number { get; set; }
        public Nullable<int> production_person_count { get; set; }
        public Nullable<int> production_workshop_number { get; set; }
        public Nullable<decimal> min_cost_for_agent { get; set; }
    
        public virtual prod_types prod_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales> sales { get; set; }
    }
}
