//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sessia1.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public int id_sale { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_agent { get; set; }
        public Nullable<System.DateTime> date_realization { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual agents agents { get; set; }
        public virtual products products { get; set; }
    }
}
